---
- name: Create containerd.conf file
  ansible.builtin.copy:
    dest: /etc/modules-load.d/containerd.conf
    content: |
      overlay
      br_netfilter
  become: true
  become_user: root

- name: Load modules
  ansible.builtin.shell: |
    modprobe overlay
    modprobe br_netfilter
  become: true
  become_user: root

- name: Add kernel parameters
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-kubernetes-cri.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.ipv4.ip_forward                 = 1
      net.bridge.bridge-nf-call-ip6tables = 1
  become: true
  become_user: root

- name: Apply sysctl parameters
  ansible.builtin.shell: |
    sysctl --system
  become: true
  become_user: root