---
- name: Get join command from master
  command: kubeadm token create --print-join-command
  register: join_command_output
  become: true
  become_user: root

- set_fact:
    join_command: "{{ join_command_output.stdout }}"