---
- name: Prepare K8S Cluster
  hosts: k8s_cluster
  become: true
  become_user: root
  roles:
    - role: system-update
    - role: k8s-preinstall

- name: Init K8S Cluster
  hosts: master_nodes
  become: true
  become_user: root
  roles:
    - role: k8s-initialize
    - role: k8s-get-join-command

- name: Join K8S Cluster
  hosts: worker_nodes
  become: true
  become_user: root
  roles:
    - role: k8s-join
