---
- name: Update /etc/hosts file
  ansible.builtin.lineinfile:
    path: "/etc/hosts"
    state: present
    owner: "root"
    line: "{{ item }}"
    insertafter: "127.0.0.1 localhost"
  become: true
  become_user: root
  with_items:
  - "{{ file_content }}"